---
#
# Playbook to register Compute Manager with NSX Appliance, Create IP Pools 
#
#
- hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - deploy_nsx_cluster_vars.yml
  tasks:
    - name: Register Compute Manager
      nsxt_fabric_compute_managers:
          hostname: "{{ nsxt_vip }}"
          username: "{{ nsx_username }}"
          password: "{{ nsx_password }}"
          validate_certs: "{{ validate_certs }}"
          display_name: "{{ item.display_name }}"
          server: "{{ item.mgmt_ip }}"
          origin_type: "{{ item.origin_type }}"
          credential:
            credential_type: "{{ item.credential_type }}"
            username: "{{ item.username }}"
            password: "{{ item.password }}"
          state: "{{ state }}"
      with_items:
        - "{{compute_managers}}"

    - name: Licensing NSX Manager
      nsxt_licenses:
        hostname: "{{ nsxt_vip }}"
        username: "{{ nsx_username }}"
        password: "{{ nsx_password }}"
        validate_certs: "{{ validate_certs }}"
        license_key: "{{ license_key }}"
        state: "{{ state }}"

        
  # Create IP Pools for NSX Edges or ESXi hosts       
    - name: Create IP Pools
      nsxt_ip_pools:
        hostname: "{{ nsxt_vip }}"
        username: "{{ nsx_username }}"
        password: "{{ nsx_password }}"
        validate_certs: "{{ validate_certs }}"
        display_name: "{{ item.display_name }}"
        subnets: "{{ item.subnets }}"
        state: "{{ state }}"
      with_items:
        - "{{ ip_pools }}"

  # Create Uplink Profiles for NSX Edges and ESXi hosts
    - name: Create NSX Edge Uplink profiles
      nsxt_uplink_profiles:
        hostname: "{{ nsxt_vip }}"
        username: "{{ nsx_username }}"
        password: "{{ nsx_password }}"
        validate_certs: False
        resource_type: UplinkHostSwitchProfile
        display_name: "{{ item.display_name }}"
        teaming: "{{ item.teaming }}"
        transport_vlan: "{{ item.transport_vlan }}"
        mtu: "{{ item.mtu }}"
        state: "{{ state }}"
        named_teamings: "{{ item.named_teamings }}"
      with_items:
        - "{{ edge_uplink_profiles }}"

  # Create Uplink Profiles for NSX Edges and ESXi hosts
    - name: Create ESXi Host Uplink profiles
      nsxt_uplink_profiles:
        hostname: "{{ nsxt_vip }}"
        username: "{{ nsx_username }}"
        password: "{{ nsx_password }}"
        validate_certs: False
        resource_type: UplinkHostSwitchProfile
        display_name: "{{ item.display_name }}"
        teaming: "{{ item.teaming }}"
        transport_vlan: "{{ item.transport_vlan }}"
        state: "{{ state }}"
        named_teamings: "{{ item.named_teamings }}"
      with_items:
        - "{{ esxi_uplink_profiles }}"

  # Create Transport Zones for NSX Edges and ESXi hosts
    - name: Create transport zones
      nsxt_transport_zones:
        hostname: "{{ nsxt_vip }}"
        username: "{{ nsx_username }}"
        password: "{{ nsx_password }}"
        validate_certs: "{{ validate_certs }}"
        resource_type: "TransportZone"
        display_name: "{{ item.display_name }}"
        description: "{{ item.description }}"
        transport_type: "{{ item.transport_type }}"
        host_switch_name: "{{ item.host_switch_name }}"
        uplink_teaming_policy_names: "{{item.uplink_teaming_policy_names}}"
        state: "{{ state }}"
      with_items:
        - "{{ transport_zones }}"
      register: tzs

  # Create Transport Node Profiles for ESXi hosts
    - name: Create Transport Node Profile
      nsxt_transport_node_profiles:
        hostname: "{{ nsxt_vip }}"
        username: "{{ nsx_username }}"
        password: "{{ nsx_password }}"
        validate_certs: "{{ validate_certs }}"
        resource_type: TransportNodeProfile
        display_name: "{{ item.display_name }}"
        description: "{{ item.description }}"
        host_switch_spec:
          resource_type: StandardHostSwitchSpec
          host_switches: "{{ item.host_switches }}"
        state: "{{ state }}"
      with_items:
        - "{{ transport_node_profiles }}"

  # Attach TN Profile to vSphere Cluster and Prepare ESXi
    - name: Attach Transport Node Profile to cluster
      nsxt_transport_node_collections:
        hostname: "{{ nsxt_vip }}"
        username: "{{ nsx_username }}"
        password: "{{ nsx_password }}"
        validate_certs: "{{ validate_certs }}"
        display_name: "TNC"
        resource_type: "TransportNodeCollection"
        description: "Transport Node Collections Hosts"
        compute_manager_name: "{{compute_managers[0].display_name}}"
        cluster_name: "Sector-A"
        transport_node_profile_name: "{{transport_node_profiles[0].display_name}}"
        state: "{{ state }}"